### ISSUE TITLE
Update README.MD 

### ISSUE THREAD

**Issue by DhanushNehru** [DhanushNehru/breakout-game#10]
Update README.MD with more clear explanation & updated images / gifs

**Comment by ikurotime** [comment]
Hello! Can I work on this?

**Comment by Deep1Shikha** [comment]
@ikurotime , I have been working on this, My PR is under review. 
https://github.com/DhanushNehru/breakout-game/pull/16

**Comment by selemondev** [comment]
Hello there @Deep1Shikha 👋, sure, you can work on this issue but first make sure to update your fork. Happy coding 😄.

**Comment by selemondev** [comment]
This issue has finally been resolved, thank you, everyone for contributing to this issue.
