### ISSUE TITLE
Collision detection allows ball to partially go through bricks

### ISSUE THREAD

**Issue by tygee713** [DhanushNehru/breakout-game#29]
When watching the gif in the readme and trying out the game, I noticed that half of the ball could go through a brick before the game recognizes that it made contact, and a ball hitting a corner of a brick would not collide at all. If it's alright, I'm going to work on a PR to fix this behavior.

**Comment by DhanushNehru** [comment]
Sure @tygee713

**Comment by selemondev** [comment]
This issue has finally been resolved. Thank you @tygee713 for your contribution ✨.
