### ISSUE TITLE
Out of alignment 

### ISSUE THREAD

**Issue by DhanushNehru** [DhanushNehru/breakout-game#5]
Currently the blocks in the right side are not properly aligned. Make it similar to how the blocks are in left

![IMG_20221002_141754](https://user-images.githubusercontent.com/22955675/193445980-6ea34705-1006-468b-b665-bb60ae17a526.jpg)

**Comment by ahmedsilat44** [comment]
A possible fix could be decreasing the number of columns by 1

**Comment by DhanushNehru** [comment]
Should be tried out

**Comment by DanteCuevas** [comment]
assigne to me pls

**Comment by DanteCuevas** [comment]
> assigne to me pls
I can't push pls add me to the repo
ERROR: Permission to DhanushNehru/breakout-game.git denied to DanteCuevas.

**Comment by DanteCuevas** [comment]
I made a PR review pls
