### ISSUE TITLE
Add Contribution.MD

### ISSUE THREAD

**Issue by DhanushNehru** [DhanushNehru/breakout-game#9]
Add contribution guidelines for this breakout game

**Comment by AdarshCoder397** [comment]
Hey @DhanushNehru , I can work on this issue!

**Comment by selemondev** [comment]
Hello there @AdarshCoder397 👋, this issue has been assigned to you but first make sure to update your fork so as to get the latest repository changes. Happy coding 😄.

**Comment by selemondev** [comment]
This issue has finally been resolved, thank you @Madhvik007 for your contribution and @AdarshCoder397 for your interest in contributing to this issue.
